---
collections:
  posts:
    output: true
    permalink: "/:categories/:title/"
exclude:
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
- vendor
show_drafts: ''
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
port: 4000
permalink: "/:categories/:title/"
timezone: America/New_York
kramdown:
  auto_ids: true
  footnote_nr: '1'
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    coderay_wrap: div
    coderay_line_numbers: nil
    coderay_line_number_start: '1'
    coderay_tab_width: '4'
    coderay_bold_every: '10'
    coderay_css: class
    coderay_line_numbers_start: '1'
title: Site Title
description: Describe your website here.
disqus_shortname: ''
reading_time: false
words_per_minute: 200
url: ''
owner:
  name: Your Name
  avatar: avatar.jpg
  bio: Your bio goes here. It shouldn't be super long but a good two sentences or
    two should suffice.
  email: you@email.com
  twitter: ''
  facebook: ''
  github: ''
  stackexchange: ''
  linkedin: ''
  instagram: ''
  flickr: ''
  tumblr: ''
  google_plus: ''
background: ''
google_analytics: ''
google_verify: ''
bing_verify: ''
sass:
  sass_dir: _sass
  style: compressed
paginate: 5
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: false
